/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'deleteMyProgress' : IDL.Func([], [], []),
  'loadProgress' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
  'saveProgress' : IDL.Func([IDL.Text], [], []),
  'createRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getRoom' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'deleteRoom' : IDL.Func([IDL.Text], [], []),
  'setChatMessages' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getChatMessages' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'deleteMyProgress' : IDL.Func([], [], []),
    'loadProgress' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
    'saveProgress' : IDL.Func([IDL.Text], [], []),
    'createRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getRoom' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'deleteRoom' : IDL.Func([IDL.Text], [], []),
    'setChatMessages' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getChatMessages' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
